-- MySQL Script generated by MySQL Workbench
-- 11/05/14 11:13:51
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema espumred
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `espumred` ;
CREATE SCHEMA IF NOT EXISTS `espumred` DEFAULT CHARACTER SET utf8 ;
USE `espumred` ;

-- -----------------------------------------------------
-- Table `espumred`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`area` (
  `id` VARCHAR(45) NOT NULL,
  `nombreArea` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`articulos` (
  `id` VARCHAR(45) NOT NULL,
  `Nombre_Articulo` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Valor` INT(11) NOT NULL,
  `Fecha_Creacion` DATETIME NULL DEFAULT NULL,
  `Fecha_Modificacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`articulosdedotacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`articulosdedotacion` (
  `id` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `tipoDotacion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`lote` (
  `codLote` VARCHAR(45) NOT NULL,
  `tipoEspuma` VARCHAR(45) NULL DEFAULT NULL,
  `densidad` VARCHAR(45) NULL DEFAULT NULL,
  `altura` VARCHAR(45) NULL DEFAULT NULL,
  `ancho` VARCHAR(45) NULL DEFAULT NULL,
  `largo` VARCHAR(45) NULL DEFAULT NULL,
  `peso` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `Fecha_Creacion` DATETIME NULL DEFAULT NULL,
  `Fecha_Modificacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`codLote`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`cargarespumas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`cargarespumas` (
  `id` VARCHAR(45) NOT NULL,
  `altura` VARCHAR(45) NULL DEFAULT NULL,
  `ancho` VARCHAR(45) NULL DEFAULT NULL,
  `largo` VARCHAR(45) NULL DEFAULT NULL,
  `densidad` VARCHAR(45) NULL DEFAULT NULL,
  `cantidadKilo` VARCHAR(45) NULL DEFAULT NULL,
  `codlote` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `codigosap` VARCHAR(45) NULL DEFAULT NULL,
  `Fecha_Creacion` DATETIME NULL DEFAULT NULL,
  `Fecha_Modificacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `codlote`
    FOREIGN KEY (`codlote`)
    REFERENCES `espumred`.`lote` (`codLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `codlote_idx` ON `espumred`.`cargarespumas` (`codlote` ASC);


-- -----------------------------------------------------
-- Table `espumred`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`cargos` (
  `id` VARCHAR(45) NOT NULL,
  `nombreCargo` VARCHAR(45) NULL DEFAULT NULL,
  `codigoSena` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`usuario` (
  `id` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `CC` INT(11) NOT NULL,
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  `Fecha_Creacion` DATETIME NULL DEFAULT NULL,
  `Fecha_Modificacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`ciudad` (
  `id` VARCHAR(45) NOT NULL,
  `NombreCiudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`empresa` (
  `id` VARCHAR(45) NOT NULL,
  `NombreEmpresa` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`cartaremisora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`cartaremisora` (
  `id` VARCHAR(45) NOT NULL,
  `idArticulo` VARCHAR(45) NULL DEFAULT NULL,
  `idCliente` VARCHAR(45) NULL DEFAULT NULL,
  `idUsuario` VARCHAR(45) NULL DEFAULT NULL,
  `Direccion` VARCHAR(45) NULL DEFAULT NULL,
  `Telefono` VARCHAR(20) NULL DEFAULT NULL,
  `Ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `Flete_Pagadero` VARCHAR(45) NULL DEFAULT NULL,
  `Numero_Factura` VARCHAR(45) NULL DEFAULT NULL,
  `Cantidad_Articulo` INT(11) NULL DEFAULT NULL,
  `Valor_Unitario_Articulo` INT(11) NULL DEFAULT NULL,
  `Valor_Total` INT(11) NULL DEFAULT NULL,
  `Numero_Bultos` VARCHAR(45) NULL DEFAULT NULL,
  `Fecha_Creacion` DATETIME NULL DEFAULT NULL,
  `Fecha_Modificacion` DATETIME NULL DEFAULT NULL,
  `descripcion` VARCHAR(10000) NULL DEFAULT NULL,
  `consecutivo` INT(11) NULL DEFAULT NULL,
  `Empresa` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `Fk_idArticulo`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `espumred`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `espumred`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_ciudad`
    FOREIGN KEY (`Ciudad`)
    REFERENCES `espumred`.`ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_empresa`
    FOREIGN KEY (`Empresa`)
    REFERENCES `espumred`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_idArticulo_idx` ON `espumred`.`cartaremisora` (`idArticulo` ASC);

CREATE INDEX `Fk_idUsuario_idx` ON `espumred`.`cartaremisora` (`idUsuario` ASC);

CREATE INDEX `Fk_ciudad_idx` ON `espumred`.`cartaremisora` (`Ciudad` ASC);

CREATE INDEX `Fk_empresa_idx` ON `espumred`.`cartaremisora` (`Empresa` ASC);


-- -----------------------------------------------------
-- Table `espumred`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`cliente` (
  `id` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Apellido` VARCHAR(45) NULL DEFAULT NULL,
  `CC` INT(11) NULL DEFAULT NULL,
  `Direccion` VARCHAR(45) NULL DEFAULT NULL,
  `Telefono` VARCHAR(20) NULL DEFAULT NULL,
  `Fecha_Creacion` DATETIME NULL DEFAULT NULL,
  `Fecha_Modificacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`contrato` (
  `id` VARCHAR(45) NOT NULL,
  `tipoContrato` VARCHAR(45) NULL DEFAULT NULL,
  `fechaPrimerContrato` VARCHAR(45) NULL DEFAULT NULL,
  `fechaIngreso` VARCHAR(45) NULL DEFAULT NULL,
  `fechaDeRetiro` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`descargoespumas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`descargoespumas` (
  `id` VARCHAR(45) NOT NULL,
  `numeroLote` VARCHAR(45) NULL DEFAULT NULL,
  `cantidadConsumida` VARCHAR(45) NULL DEFAULT NULL,
  `codsap` VARCHAR(45) NULL DEFAULT NULL,
  `Fecha_Creacion` DATETIME NULL DEFAULT NULL,
  `idCargarespumas` VARCHAR(45) NULL DEFAULT NULL,
  `Fecha_Modificacion` DATETIME NULL DEFAULT NULL,
  `altura` VARCHAR(45) NULL DEFAULT NULL,
  `ancho` VARCHAR(45) NULL DEFAULT NULL,
  `largo` VARCHAR(45) NULL DEFAULT NULL,
  `densidad` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `descargo`
    FOREIGN KEY (`idCargarespumas`)
    REFERENCES `espumred`.`cargarespumas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `descargo_idx` ON `espumred`.`descargoespumas` (`idCargarespumas` ASC);


-- -----------------------------------------------------
-- Table `espumred`.`dotacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`dotacion` (
  `id` VARCHAR(45) NOT NULL,
  `camisa` VARCHAR(45) NULL DEFAULT NULL,
  `calsado` VARCHAR(45) NULL DEFAULT NULL,
  `pantalon` VARCHAR(45) NULL DEFAULT NULL,
  `delantal` VARCHAR(45) NULL DEFAULT NULL,
  `overol` VARCHAR(45) NULL DEFAULT NULL,
  `botas` VARCHAR(45) NULL DEFAULT NULL,
  `tenis` VARCHAR(45) NULL DEFAULT NULL,
  `otrasDotaciones` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`espumas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`espumas` (
  `cod` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `ancho` VARCHAR(45) NULL DEFAULT NULL,
  `largo` VARCHAR(45) NULL DEFAULT NULL,
  `alto` VARCHAR(45) NULL DEFAULT NULL,
  `densidad` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`estadoestudiantil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`estadoestudiantil` (
  `id` VARCHAR(45) NOT NULL,
  `tituloCarrera` VARCHAR(45) NULL DEFAULT NULL,
  `semestreActual` VARCHAR(45) NULL DEFAULT NULL,
  `FechaTerminacion` VARCHAR(45) NULL DEFAULT NULL,
  `estadoEstudiante` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`extensiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`extensiones` (
  `id` VARCHAR(45) NOT NULL,
  `area` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `correoElectronico` VARCHAR(45) NULL DEFAULT NULL,
  `skype` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`formacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`formacion` (
  `cod` VARCHAR(45) NOT NULL,
  `codlote` VARCHAR(45) NULL DEFAULT NULL,
  `altura` VARCHAR(45) NULL DEFAULT NULL,
  `ancho` VARCHAR(45) NULL DEFAULT NULL,
  `largo` VARCHAR(45) NULL DEFAULT NULL,
  `peso` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` VARCHAR(45) NULL DEFAULT NULL,
  `Fecha_Creacion` DATETIME NULL DEFAULT NULL,
  `Fecha_Modificacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`cod`),
  CONSTRAINT `numerolote`
    FOREIGN KEY (`codlote`)
    REFERENCES `espumred`.`lote` (`codLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `numerolote_idx` ON `espumred`.`formacion` (`codlote` ASC);


-- -----------------------------------------------------
-- Table `espumred`.`herramientas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`herramientas` (
  `id` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `fechaDeCompra` VARCHAR(45) NULL DEFAULT NULL,
  `proveedor` VARCHAR(45) NULL DEFAULT NULL,
  `fechaDeBaja` VARCHAR(45) NULL DEFAULT NULL,
  `fabricante` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`informacionacademica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`informacionacademica` (
  `id` VARCHAR(45) NOT NULL,
  `nombreEmpleado` VARCHAR(45) NULL DEFAULT NULL,
  `escolaridad` VARCHAR(45) NULL DEFAULT NULL,
  `tituloObtenido` VARCHAR(45) NULL DEFAULT NULL,
  `institucion` VARCHAR(45) NULL DEFAULT NULL,
  `primerCurso` VARCHAR(45) NULL DEFAULT NULL,
  `segundoCurso` VARCHAR(45) NULL DEFAULT NULL,
  `tercerCurso` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`informacioneconomica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`informacioneconomica` (
  `id` VARCHAR(45) NOT NULL,
  `primerIngreso` VARCHAR(45) NULL DEFAULT NULL,
  `segundoIngreso` VARCHAR(45) NULL DEFAULT NULL,
  `otrosIngresos` VARCHAR(45) NULL DEFAULT NULL,
  `totalIngresos` VARCHAR(45) NULL DEFAULT NULL,
  `arriendo` VARCHAR(45) NULL DEFAULT NULL,
  `serviciosPublicos` VARCHAR(45) NULL DEFAULT NULL,
  `internet` VARCHAR(45) NULL DEFAULT NULL,
  `telefonia` VARCHAR(45) NULL DEFAULT NULL,
  `cable` VARCHAR(45) NULL DEFAULT NULL,
  `alimentacion` VARCHAR(45) NULL DEFAULT NULL,
  `transporte` VARCHAR(45) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NULL DEFAULT NULL,
  `educacion` VARCHAR(45) NULL DEFAULT NULL,
  `vehiculo` VARCHAR(45) NULL DEFAULT NULL,
  `prestacionesComercial` VARCHAR(45) NULL DEFAULT NULL,
  `prestamosBancario` VARCHAR(45) NULL DEFAULT NULL,
  `hipoteca` VARCHAR(45) NULL DEFAULT NULL,
  `vestidoYCalzado` VARCHAR(45) NULL DEFAULT NULL,
  `recreacion` VARCHAR(45) NULL DEFAULT NULL,
  `saldoFinal` VARCHAR(45) NULL DEFAULT NULL,
  `totalGastos` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`municipio` (
  `id` VARCHAR(45) NOT NULL,
  `nombreMunicipio` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`informacionpersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`informacionpersonal` (
  `cc` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `fechaNacimiento` VARCHAR(45) NULL DEFAULT NULL,
  `lugarNacimiento` VARCHAR(45) NULL DEFAULT NULL,
  `sexo` VARCHAR(45) NULL DEFAULT NULL,
  `rh` VARCHAR(45) NULL DEFAULT NULL,
  `estadoCivil` VARCHAR(45) NULL DEFAULT NULL,
  `tiempoCasado` VARCHAR(45) NULL DEFAULT NULL,
  `numeroHijos` VARCHAR(45) NULL DEFAULT NULL,
  `direccionResidencia` VARCHAR(45) NULL DEFAULT NULL,
  `barrio` VARCHAR(45) NULL DEFAULT NULL,
  `municipio` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NULL DEFAULT NULL,
  `libretaMilitar` VARCHAR(45) NULL DEFAULT NULL,
  `claseLibretaMilitar` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cc`),
  CONSTRAINT `fk_municipio`
    FOREIGN KEY (`municipio`)
    REFERENCES `espumred`.`municipio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_municipio_idx` ON `espumred`.`informacionpersonal` (`municipio` ASC);


-- -----------------------------------------------------
-- Table `espumred`.`seguridadsocial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`seguridadsocial` (
  `id` VARCHAR(45) NOT NULL,
  `censantias` VARCHAR(45) NULL DEFAULT NULL,
  `afp` VARCHAR(45) NULL DEFAULT NULL,
  `eps` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`informacionfamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`informacionfamiliar` (
  `id` VARCHAR(45) NOT NULL,
  `ccEmpleado` INT(11) NULL DEFAULT NULL,
  `nombreFamiliar` VARCHAR(45) NULL DEFAULT NULL,
  `parantesco` VARCHAR(45) NULL DEFAULT NULL,
  `fechaDeNacimiento` VARCHAR(45) NULL DEFAULT NULL,
  `edad` VARCHAR(45) NULL DEFAULT NULL,
  `escolaridad` VARCHAR(45) NULL DEFAULT NULL,
  `ocupacion` VARCHAR(45) NULL DEFAULT NULL,
  `viveConEmpleado` VARCHAR(45) NULL DEFAULT NULL,
  `dependeDelEmpleado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`informacionvivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`informacionvivienda` (
  `id` VARCHAR(45) NOT NULL,
  `numeroDeHabitantes` VARCHAR(45) NULL DEFAULT NULL,
  `indiceHacimiento` VARCHAR(45) NULL DEFAULT NULL,
  `estrato` VARCHAR(45) NULL DEFAULT NULL,
  `tenenciaDeLaVivienda` VARCHAR(45) NULL DEFAULT NULL,
  `tipoDeVivienda` VARCHAR(45) NULL DEFAULT NULL,
  `numeroDeHabitacion` VARCHAR(45) NULL DEFAULT NULL,
  `cocina` VARCHAR(45) NULL DEFAULT NULL,
  `bañoComun` VARCHAR(45) NULL DEFAULT NULL,
  `bañoPrivado` VARCHAR(45) NULL DEFAULT NULL,
  `sala` VARCHAR(45) NULL DEFAULT NULL,
  `comedor` VARCHAR(45) NULL DEFAULT NULL,
  `salaComedor` VARCHAR(45) NULL DEFAULT NULL,
  `zonaDeRopa` VARCHAR(45) NULL DEFAULT NULL,
  `agua` VARCHAR(45) NULL DEFAULT NULL,
  `electricidad` VARCHAR(45) NULL DEFAULT NULL,
  `gas` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `internet` VARCHAR(45) NULL DEFAULT NULL,
  `televisionPorCable` VARCHAR(45) NULL DEFAULT NULL,
  `otros` VARCHAR(45) NULL DEFAULT NULL,
  `television` VARCHAR(45) NULL DEFAULT NULL,
  `equipoDeSonido` VARCHAR(45) NULL DEFAULT NULL,
  `lavadora` VARCHAR(45) NULL DEFAULT NULL,
  `estufa` VARCHAR(45) NULL DEFAULT NULL,
  `dvd` VARCHAR(45) NULL DEFAULT NULL,
  `microondas` VARCHAR(45) NULL DEFAULT NULL,
  `pc` VARCHAR(45) NULL DEFAULT NULL,
  `piso` VARCHAR(45) NULL DEFAULT NULL,
  `techo` VARCHAR(45) NULL DEFAULT NULL,
  `paredes` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`informacionempleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`informacionempleado` (
  `id` VARCHAR(45) NOT NULL,
  `codigoNomina` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `carnet` VARCHAR(45) NULL DEFAULT NULL,
  `informacionAcademica` VARCHAR(45) NULL DEFAULT NULL,
  `informacionPersonal` INT(11) NULL DEFAULT NULL,
  `informacionFamiliar` VARCHAR(45) NULL DEFAULT NULL,
  `InformacionVivienda` VARCHAR(45) NULL DEFAULT NULL,
  `InformacionEconomica` VARCHAR(45) NULL DEFAULT NULL,
  `estadoEstudiantil` VARCHAR(45) NULL DEFAULT NULL,
  `seguridadSocial` VARCHAR(45) NULL DEFAULT NULL,
  `area` VARCHAR(45) NULL DEFAULT NULL,
  `contrato` VARCHAR(45) NULL DEFAULT NULL,
  `vehiculo` VARCHAR(45) NULL DEFAULT NULL,
  `contactoEmergencia` VARCHAR(45) NULL DEFAULT NULL,
  `telefonoContacto` VARCHAR(45) NULL DEFAULT NULL,
  `dotacion` VARCHAR(45) NULL DEFAULT NULL,
  `motivoRetiro` VARCHAR(45) NULL DEFAULT NULL,
  `cargo` VARCHAR(45) NULL DEFAULT NULL,
  `numeroCuenta` VARCHAR(45) NULL DEFAULT NULL,
  `fechaFinalizacionRetiro` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `informacionpersonal`
    FOREIGN KEY (`informacionPersonal`)
    REFERENCES `espumred`.`informacionpersonal` (`cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estadoestudiantil`
    FOREIGN KEY (`estadoEstudiantil`)
    REFERENCES `espumred`.`estadoestudiantil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seguridadsocial`
    FOREIGN KEY (`seguridadSocial`)
    REFERENCES `espumred`.`seguridadsocial` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `informacionfamiliar`
    FOREIGN KEY (`informacionFamiliar`)
    REFERENCES `espumred`.`informacionfamiliar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `area`
    FOREIGN KEY (`area`)
    REFERENCES `espumred`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contrato`
    FOREIGN KEY (`contrato`)
    REFERENCES `espumred`.`contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `informacionacademina`
    FOREIGN KEY (`informacionAcademica`)
    REFERENCES `espumred`.`informacionacademica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `informacionvivienda`
    FOREIGN KEY (`InformacionVivienda`)
    REFERENCES `espumred`.`informacionvivienda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `informacionEconomica`
    FOREIGN KEY (`InformacionEconomica`)
    REFERENCES `espumred`.`informacioneconomica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dotacion`
    FOREIGN KEY (`dotacion`)
    REFERENCES `espumred`.`dotacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cargo`
    FOREIGN KEY (`cargo`)
    REFERENCES `espumred`.`cargos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fkempleado_idx` ON `espumred`.`informacionempleado` (`informacionPersonal` ASC);

CREATE INDEX `fkestadoestudiantil_idx` ON `espumred`.`informacionempleado` (`estadoEstudiantil` ASC);

CREATE INDEX `fk_seguridadsocial_idx` ON `espumred`.`informacionempleado` (`seguridadSocial` ASC);

CREATE INDEX `fk_informacionfamiliar_idx` ON `espumred`.`informacionempleado` (`informacionFamiliar` ASC);

CREATE INDEX `fk_contrato_idx` ON `espumred`.`informacionempleado` (`contrato` ASC);

CREATE INDEX `informacionacademina_idx` ON `espumred`.`informacionempleado` (`informacionAcademica` ASC);

CREATE INDEX `informacionvivienda_idx` ON `espumred`.`informacionempleado` (`InformacionVivienda` ASC);

CREATE INDEX `informacionEconomica_idx` ON `espumred`.`informacionempleado` (`InformacionEconomica` ASC);

CREATE INDEX `dotacion_idx` ON `espumred`.`informacionempleado` (`dotacion` ASC);

CREATE INDEX `area_idx` ON `espumred`.`informacionempleado` (`area` ASC);

CREATE INDEX `cargo_idx` ON `espumred`.`informacionempleado` (`cargo` ASC);


-- -----------------------------------------------------
-- Table `espumred`.`mecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`mecanicos` (
  `cc` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Telefono` VARCHAR(20) NULL,
  `Fecha_Creacion` DATETIME NULL,
  `Fecha_Modificacion` DATETIME NULL,
  PRIMARY KEY (`cc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`prestamos` (
  `id` VARCHAR(45) NOT NULL,
  `id_Cliente` VARCHAR(45) NULL DEFAULT NULL,
  `id_Usuario` VARCHAR(45) NULL DEFAULT NULL,
  `id_Ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `id_Articulo` VARCHAR(45) NULL DEFAULT NULL,
  `valorUnitario` INT(11) NULL DEFAULT NULL,
  `valortotal` INT(11) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `Fecha_Creacion` DATETIME NULL DEFAULT NULL,
  `Fecha_Modificacion` DATETIME NULL DEFAULT NULL,
  `consecutivo` INT(11) NULL DEFAULT NULL,
  `descripcion` VARCHAR(10000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `cliente`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `espumred`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `espumred`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ciudad`
    FOREIGN KEY (`id_Ciudad`)
    REFERENCES `espumred`.`ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `articulo`
    FOREIGN KEY (`id_Articulo`)
    REFERENCES `espumred`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_cliente_idx` ON `espumred`.`prestamos` (`id_Cliente` ASC);

CREATE INDEX `fk_usuario_idx` ON `espumred`.`prestamos` (`id_Usuario` ASC);

CREATE INDEX `fk_ciudad_idx` ON `espumred`.`prestamos` (`id_Ciudad` ASC);

CREATE INDEX `fk_articulo_idx` ON `espumred`.`prestamos` (`id_Articulo` ASC);


-- -----------------------------------------------------
-- Table `espumred`.`productocostos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`productocostos` (
  `cod` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `medidas` VARCHAR(45) NULL DEFAULT NULL,
  `calibre` VARCHAR(45) NULL DEFAULT NULL,
  `precioMayoristas` VARCHAR(45) NULL DEFAULT NULL,
  `precioCorreria` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`registro` (
  `id` VARCHAR(45) NOT NULL,
  `idMecanico` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `cantidad` VARCHAR(45) NULL,
  `ubicacion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `mecanico`
    FOREIGN KEY (`idMecanico`)
    REFERENCES `espumred`.`mecanicos` (`cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `mecanico_idx` ON `espumred`.`registro` (`idMecanico` ASC);


-- -----------------------------------------------------
-- Table `espumred`.`reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`reporte` (
  `id` VARCHAR(45) NOT NULL,
  `fechaFormacion` VARCHAR(45) NULL DEFAULT NULL,
  `fechaCorte` VARCHAR(45) NULL DEFAULT NULL,
  `codSap` VARCHAR(45) NULL DEFAULT NULL,
  `lote` VARCHAR(45) NULL DEFAULT NULL,
  `tipoEspumas` VARCHAR(45) NULL DEFAULT NULL,
  `densidad` VARCHAR(45) NULL DEFAULT NULL,
  `color` VARCHAR(45) NULL DEFAULT NULL,
  `ancho` VARCHAR(45) NULL DEFAULT NULL,
  `alto` VARCHAR(45) NULL DEFAULT NULL,
  `largo` VARCHAR(45) NULL DEFAULT NULL,
  `kilo` VARCHAR(45) NULL DEFAULT NULL,
  `metroConforme` VARCHAR(45) NULL DEFAULT NULL,
  `metroNoConforme` VARCHAR(45) NULL DEFAULT NULL,
  `kiloConforme` VARCHAR(45) NULL DEFAULT NULL,
  `kiloNoConforme` VARCHAR(45) NULL DEFAULT NULL,
  `motivo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`repuestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`repuestos` (
  `id` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `fechaDeCompra` VARCHAR(45) NULL DEFAULT NULL,
  `proveedor` VARCHAR(45) NULL DEFAULT NULL,
  `fechaDeBaja` VARCHAR(45) NULL DEFAULT NULL,
  `fabricante` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `espumred`.`facturacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`facturacion` (
  `id` VARCHAR(45) NOT NULL,
  `provedor` VARCHAR(45) NULL,
  `numeroFactura` VARCHAR(45) NULL,
  `valorFactura` VARCHAR(45) NULL,
  `consecutivo` VARCHAR(45) NULL,
  `idUsuario` VARCHAR(45) NULL,
  `observacion` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `Fecha_Creacion` DATETIME NULL DEFAULT NULL,
  `Fecha_Modificacion` DATETIME NULL DEFAULT NULL,
  `Fecha_Vencimiento` VARCHAR(45) NULL,
  `Fecha_Envio` VARCHAR(45) NULL,
  `Fecha_Pagado` VARCHAR(45) NULL,
  `correoelectronico` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `espumred`.`provedoresfacturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espumred`.`provedoresfacturas` (
  `id` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `codigoPago` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `correoelectronico` VARCHAR(45) NULL,
  `Fecha_Creacion` DATETIME NULL DEFAULT NULL,
  `Fecha_Modificacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
