-- MySQL Script generated by MySQL Workbench
-- 07/21/14 16:01:13
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProyectoDespacho
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProyectoDespacho` ;
CREATE SCHEMA IF NOT EXISTS `ProyectoDespacho` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ProyectoDespacho` ;

-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Usuario` (
  `id` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `CC` INT NOT NULL,
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  `Fecha_Creacion` DATETIME NULL,
  `Fecha_Modificacion` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Cliente` (
  `id` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apelliido` VARCHAR(45) NULL,
  `CC` INT NULL,
  `Direccion` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Fecha_Creacion` DATETIME NULL,
  `Fecha_Modificacion` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Articulos` (
  `id` VARCHAR(45) NOT NULL,
  `Nombre_Articulo` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Valor` INT NOT NULL,
  `Fecha_Creacion` DATETIME NULL,
  `Fecha_Modificacion` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Ciudad` (
  `id` VARCHAR(45) NOT NULL,
  `NombreCiudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Empresa` (
  `id` VARCHAR(45) NOT NULL,
  `NombreEmpresa` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`CartaRemisora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`CartaRemisora` (
  `id` VARCHAR(45) NOT NULL,
  `idArticulo` VARCHAR(45) NULL,
  `idCliente` VARCHAR(45) NULL,
  `idUsuario` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Flete_Pagadero` VARCHAR(45) NULL,
  `Numero_Factura` VARCHAR(45) NULL,
  `Cantidad_Articulo` INT NULL,
  `Valor_Unitario_Articulo` INT NULL,
  `Valor_Total` INT NULL,
  `Numero_Bultos` VARCHAR(45) NULL,
  `Fecha_Creacion` DATETIME NULL,
  `Fecha_Modificacion` DATETIME NULL,
  `descripcion` VARCHAR(10000) NULL,
  `consecutivo` INT NULL,
  `Empresa` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `Fk_idArticulo`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `ProyectoDespacho`.`Articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `ProyectoDespacho`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `ProyectoDespacho`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_ciudad`
    FOREIGN KEY (`Ciudad`)
    REFERENCES `ProyectoDespacho`.`Ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_empresa`
    FOREIGN KEY (`Empresa`)
    REFERENCES `ProyectoDespacho`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_idArticulo_idx` ON `ProyectoDespacho`.`CartaRemisora` (`idArticulo` ASC);

CREATE INDEX `Fk_idCliente_idx` ON `ProyectoDespacho`.`CartaRemisora` (`idCliente` ASC);

CREATE INDEX `Fk_idUsuario_idx` ON `ProyectoDespacho`.`CartaRemisora` (`idUsuario` ASC);

CREATE INDEX `Fk_ciudad_idx` ON `ProyectoDespacho`.`CartaRemisora` (`Ciudad` ASC);

CREATE INDEX `Fk_empresa_idx` ON `ProyectoDespacho`.`CartaRemisora` (`Empresa` ASC);


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Prestamos` (
  `id` VARCHAR(45) NOT NULL,
  `id_Cliente` VARCHAR(45) NULL,
  `id_Usuario` VARCHAR(45) NULL,
  `id_Ciudad` VARCHAR(45) NULL,
  `id_Articulo` VARCHAR(45) NULL,
  `valorUnitario` INT NULL,
  `valortotal` INT NULL,
  `cantidad` INT NULL,
  `Fecha_Creacion` DATETIME NULL,
  `Fecha_Modificacion` DATETIME NULL,
  `consecutivo` INT NULL,
  `descripcion` VARCHAR(10000) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `cliente`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `ProyectoDespacho`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `ProyectoDespacho`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ciudad`
    FOREIGN KEY (`id_Ciudad`)
    REFERENCES `ProyectoDespacho`.`Ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `articulo`
    FOREIGN KEY (`id_Articulo`)
    REFERENCES `ProyectoDespacho`.`Articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cliente_idx` ON `ProyectoDespacho`.`Prestamos` (`id_Cliente` ASC);

CREATE INDEX `fk_usuario_idx` ON `ProyectoDespacho`.`Prestamos` (`id_Usuario` ASC);

CREATE INDEX `fk_ciudad_idx` ON `ProyectoDespacho`.`Prestamos` (`id_Ciudad` ASC);

CREATE INDEX `fk_articulo_idx` ON `ProyectoDespacho`.`Prestamos` (`id_Articulo` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
