INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'26	','VALETA _41','CALZADO');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'25	','VALETA_34','CALZADO');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002243',	'BLUJEAN_28','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002244',	'BLUJEAN_30','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002245',	'BLUJEAN_32','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002246',	'BLUJEAN_34','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002247',	'BLUJEAN_36','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002248',	'BLUJEAN_38','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002249',	'BLUJEAN_40','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002250',	'BLUJEAN_42','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002213',	'BLUSA DAMA_10','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002214',	'BLUSA DAMA_12','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002215',	'BLUSA DAMA_14','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002216',	'BLUSA DAMA_16','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002217',	'BLUSA DAMA_18','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002211',	'BLUSA DAMA_6','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002212',	'BLUSA DAMA_8','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002495',	'BOTAS PLASTICAS_39','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002496',	'BOTAS PLASTICAS_40','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002497',	'BOTAS PLASTICAS_41','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002494',	'BOTAS SUPER_38','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'75',	'BOTAS SUPER_39','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'74',	'BOTAS SUPER_40','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'73',	'BOTAS SUPER_41','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002498',	'BOTAS SUPER_42','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002583',	'BOTAS_36','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002039',	'BOTAS_37','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002033',	'BOTAS_38','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50000170',	'BOTAS_39','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50000219',	'BOTAS_40','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002038',	'BOTAS_41','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50000220',	'BOTAS_42','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002291',	'BOTAS_43','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50000221',	'BOTAS_44','BOTAS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002288',	'CAMISA BRIGADA_L','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002287',	'CAMISA BRIGADA_M','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002286',	'CAMISA BRIGADA_S','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002289',	'CAMISA BRIGADA_XL','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002227',	'CAMISA HOMBRE_L','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002226',	'CAMISA HOMBRE_M','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002225',	'CAMISA HOMBRE_S','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002228',	'CAMISA HOMBRE_XL','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002241',	'CAMISETA_L','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002240',	'CAMISETA_M','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002239',	'CAMISETA_S','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002242',	'CAMISETA_XL','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'76',	'CAMISETA_XXL','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002324',	'CHALECO AZUL_L','OTROS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002322',	'CHALECO AZUL_M','OTROS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002424',	'CHALECO AZUL_S','OTROS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002323',	'CHALECO AZUL_XL','OTROS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002237',	'CHALECO NARANJA_L','OTROS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002236',	'CHALECO NARANJA_M','OTROS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002235',	'CHALECO NARANJA_S','OTROS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002238',	'CHALECO NARANJA_XL','OTROS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002683',	'CHALECO ROJO_XS','DELANTAL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002584',	'DELANTAL AZUL_L','DELANTAL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002252',	'DELANTAL AZUL_M','DELANTAL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002251',	'DELANTAL AZUL_S','DELANTAL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002682',	'DELANTAL AZUL_XL','DELANTAL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002501',	'DELANTAL BLANCO_L','DELANTAL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002500',	'DELANTAL BLANCO_M','DELANTAL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002499',	'DELANTAL BLANCO_S','DELANTAL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002502',	'DELANTAL BLANCO_XL','DELANTAL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002260',	'DELANTAL NARANJA_L','DELANTAL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002259',	'DELANTAL NARANJA_M','DELANTAL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002258',	'DELANTAL NARANJA_S','DELANTAL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002261',	'DELANTAL NARANJA_XL','DELANTAL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002505',	'OVEROL_L','OVEROL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002504',	'OVEROL_M','OVEROL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002503',	'OVEROL_S','OVEROL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002506',	'OVEROL_XL','OVEROL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002641',	'OVEROL_XXL','OVEROL');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002220',	'PANTALON DAMA_10','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002221',	'PANTALON DAMA_12','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002222',	'PANTALON DAMA_14','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002223',	'PANTALON DAMA_16','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002224',	'PANTALON DAMA_18','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002218',	'PANTALON DAMA_6','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002219',	'PANTALON DAMA_8','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002229',	'PANTALON HOMBRE_30','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002230',	'PANTALON HOMBRE_32','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002231',	'PANTALON HOMBRE_34','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002232',	'PANTALON HOMBRE_36','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002233',	'PANTALON HOMBRE_38','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002234',	'PANTALON HOMBRE_40','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50000231',	'POLO BLANCA_L','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50000232',	'POLO BLANCA_M','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002080',	'POLO BLANCA_S','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002081',	'POLO BLANCA_XL','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002274',	'POLO BLANCA_XS','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'77',	'POLO BLANCA_XXL','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50000234',	'POLO GRIS_L','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50000233',	'POLO GRIS_M','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002046',	'POLO GRIS_S','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002045',	'POLO GRIS_XL','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002602',	'POLO GRIS_XXL','CAMISA');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002284',	'SUDADERA_L','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002283',	'SUDADERA_M','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002282',	'SUDADERA_S','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002285',	'SUDADERA_XL','PANTALON');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002325',	'TENIS_34','TENIS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002588',	'TENIS_35','TENIS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002631',	'TENIS_36','TENIS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002632',	'TENIS_37','TENIS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002263',	'TENIS_38','TENIS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002264',	'TENIS_39','TENIS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002265',	'TENIS_40','TENIS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002266',	'TENIS_41','TENIS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002267',	'TENIS_42','TENIS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002268',	'TENIS_43','TENIS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002480',	'TENIS_44','TENIS');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002253',	'VALETA  _35','CALZADO');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002254',	'VALETA  _36','CALZADO');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002255',	'VALETA _37','CALZADO');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002256',	'VALETA _38','CALZADO');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002681',	'VALETA _39','CALZADO');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002589',	'VALETA _40','CALZADO');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50002326',	'VALETA _42','CALZADO');
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'1','PANTALON HOMBRE_28','PANTALON');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'2','SUDADERA_XXL','PANTALON');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'3','BOTAS SUPER_34','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'4','BOTAS SUPER_35','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'5','BOTAS SUPER_36','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'6','BOTAS SUPER_37','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'7','BOTAS SUPER_43','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'8','BOTAS SUPER_44','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'9','BOTAS SUPER_45','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'10','BOTAS_45','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'11','TENIS_38','TENIS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'12','TENIS_45','TENIS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'13','TENIS_45','TENIS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'14','TENIS BLANCO_34','TENIS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'15','TENIS BLANCO_35','TENIS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'16','TENIS BLANCO_36','TENIS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'17','TENIS BLANCO_37','TENIS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'18','TENIS BLANCO_38','TENIS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'19','TENIS BLANCO_39','TENIS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'20','TENIS BLANCO_40','TENIS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'21','TENIS BLANCO_41','TENIS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'22','TENIS BLANCO_42','TENIS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'23','TENIS BLANCO_43','TENIS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'24','TENIS BLANCO_44','TENIS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'27','BOTAS PLASTICAS_38','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'28','BOTAS PLASTICAS_42','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'29','BOTAS PLASTICAS_43','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'30','BOTAS PLASTICAS_44','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'31','BOTAS PLASTICAS_45','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'32','CHALECO AZUL_XS','OTROS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'33','CHALECO AZUL_XXL','OTROS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'34','CHALECO NARANJA_XS','OTROS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'35','CHALECO NARANJA_XXL','OTROS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'36','CHALECO ROJO_S','OTROS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'37','CHALECO ROJO_M','OTROS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'38','CHALECO ROJO_L','OTROS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'39','CHALECO ROJO_XL','OTROS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'40','CHALECO ROJO_XXL','OTROS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'41','CAMISA BRIGADA_XXL','CAMISA');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'42','PANTALON BRIGADA_8','PANTALON');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'43','PANTALON BRIGADA_28','PANTALON');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'44','PANTALON BRIGADA_30','PANTALON');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'45','PANTALON BRIGADA_32','PANTALON');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'46','PANTALON BRIGADA_34','PANTALON');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'47','PANTALON BRIGADA_36','PANTALON');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'48','PANTALON BRIGADA_38','PANTALON');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'49','PANTALON BRIGADA_40','PANTALON');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'50','PANTALON BRIGADA_42','PANTALON');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'51','CAMISA CONFECCION HOMBRE_S','CAMISA');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'52','CAMISA CONFECCION HOMBRE_M','CAMISA');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'53','CAMISA CONFECCION HOMBRE_L','CAMISA');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'54','CAMISA CONFECCION HOMBRE_XL','CAMISA');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'55','CAMISA CONFECCION HOMBRE_XXL','CAMISA');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'56','CAMISA CONFECCION DAMA_S','CAMISA');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'57','CAMISA CONFECCION DAMA_M','CAMISA');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'58','CAMISA CONFECCION DAMA_L','CAMISA');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'59','CAMISA CONFECCION DAMA_XL','CAMISA');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'60','SUDADERA CONFECCION_S','PANTALON');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'61','SUDADERA CONFECCION_M','PANTALON');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'62','SUDADERA CONFECCION_L','PANTALON');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'63','SUDADERA CONFECCION_XL','PANTALON');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'64','SUDADERA CONFECCION_XXL','PANTALON');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'65','BOTAS BLANCAS_38','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'66','BOTAS BLANCAS_39','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'67','BOTAS BLANCAS_40','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'68','BOTAS BLANCAS_41','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'69','BOTAS BLANCAS_42','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'70','BOTAS BLANCAS_43','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'71','BOTAS BLANCAS_44','BOTAS');	
INSERT INTO `proyectodespacho`.`articulosdedotacion` (`id`, `nombre`,`tipoDotacion`) VALUES (	'72','BOTAS BLANCAS_45','BOTAS');	