INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'1','AUXILIAR DE SISTEMAS','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'2','ANALISTA CONTABLE ','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'3','ANALISTA DE CARTERA','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'4','ANALISTA DE CARTERA 2','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'5','ANALISTA DE TALENTO HUMANO','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'6','ANALISTA DE TALENTO HUMANO (2)','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'7','ASESOR COMERCIAL AREA METROPOLITANA','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'8','ASESOR COMERCIAL FORANEO ','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'9','ASESOR COMERCIAL SALA DE VENTAS ','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'10','ASISTENTE DE COMPRAS','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'11','ASISTENTE DE GERENCIA GENERAL','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'12','ASISTENTE DE MANTENIMIENTO ','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'13','ASISTENTE DE MERCADEO','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'14','ASISTENTE DE PRODUCCION DE ESPUMA','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'15','AUDITOR INTERNO','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'16','AUXILIAR CONTABLE','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'17','AUXILIAR DE ALMACEN','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'18','AUXILIAR DE AUDITORIA Y CONTROL ','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'19','AUXILIAR DE CONTROL','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'20','AUXILIAR DE CONTROL INTERNO','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'21','AUXILIAR DE COSTOS','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'22','AUXILIAR DE DESPACHOS','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'23','AUXILIAR DE FACTURACION','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'24','AUXILIAR DE MANTENIENTO','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'25','AUXILIAR DE PEDIDOS ','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'26','AUXILIAR DE SERVICIO AL CLIENTE','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'27','AYUDANTE MAQUINA CARRUSEL','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'28','COORDINADOR DE CALIDAD','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'29','COORDINADOR DE HIPER MERCADOS','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'30','COORDINADOR DE MERCADEO Y PUBLICIDAD','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'31','COORDINADOR DE SERVICIO AL CLIENTE','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'32','COORDINADOR DE SISTEMAS ','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'33','EJECUTIVA DE GRANDES CUENTAS','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'34','GERENTE ADMINISTRATIVO','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'35','GERENTE COMERCIAL','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'36','GERENTE DE CARTERA','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'37','GERENTE FINANCIERO','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'38','GERENTE NACIONAL DE MERCADEO','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'39','JEFE  DE DESPACHOS Y PRODUCTO TERMINADO','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'40','JEFE  DE MANTENIMIENTO','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'41','JEFE DE ALMACEN','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'42','JEFE DE COMPRAS','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'43','JEFE DE COSTOS E INVENTARIOS','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'44','JEFE DE PLANTA','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'45','JEFE DE PRODUCCION DE ESPUMA','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'46','JEFE DE SEGURIDAD INDUSTRIAL Y SALUD OCUPACIONAL','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'47','MAQUINISTA DE CORTE','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'48','NOTIFICADOR','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'49','NOTIFICADOR  T8','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'50','OPERARIO ACOLCHADOR','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'51','OPERARIO ARMADOR DE MUEBLES','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'52','OPERARIO CORTADOR DE TELA','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'53','OPERARIO DE BODEGA','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'54','OPERARIO DE CORTE DE MADERA','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'55','OPERARIO DE MANEJO DE PRODUCTOS QUIMICOS','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'56','OPERARIO DE MAQUINA PLANA','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'57','OPERARIO DE PEGADO ','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'58','OPERARIO EMPACADOR','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'59','OPERARIO EMPACADOR ','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'60','OPERARIO FORRADOR DE MUEBLES','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'61','OPERARIO MAQUINA CERRADORA','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'62','OPERARIO VESTIDOR','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'63','PATINADOR','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'64','PLANIFICADOR','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'65','PLANILLADOR','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'66','PRACTICANTE SALA DE VENTAS','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'67','PROMOTOR SALA DE VENTAS','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'68','RECEPCIONISTA','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'69','REVISOR FISCAL','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'70','SECRETARIA DE GERENCIA ADMINISTRATIVA','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'71','SECRETARIA DE GERENCIA COMERCIAL','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'72','SECRETARIA DE GERENCIA GENERAL','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'73','SUPERVISOR DE CONFECCIONADO','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'74','SUPERVISOR DE CORTE','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'75','SUPERVISOR DE DESPACHOS Y PRODUCTO TERMINADO','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'76','SUPERVISOR DE MUEBLES','');
INSERT INTO `proyectodespacho`.`cargos` (`id`, `nombreCargo`, `codigoSena` ) VALUES (	'77','TESORERA','');
