-- MySQL Script generated by MySQL Workbench
-- 08/28/14 11:53:31
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProyectoDespacho
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProyectoDespacho` ;
CREATE SCHEMA IF NOT EXISTS `ProyectoDespacho` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ProyectoDespacho` ;

-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Usuario` (
  `id` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `CC` INT NOT NULL,
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  `Fecha_Creacion` DATETIME NULL,
  `Fecha_Modificacion` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Cliente` (
  `id` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `CC` INT NULL,
  `Direccion` VARCHAR(45) NULL,
  `Telefono` VARCHAR(20) NULL,
  `Fecha_Creacion` DATETIME NULL,
  `Fecha_Modificacion` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Articulos` (
  `id` VARCHAR(45) NOT NULL,
  `Nombre_Articulo` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Valor` INT NOT NULL,
  `Fecha_Creacion` DATETIME NULL,
  `Fecha_Modificacion` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Ciudad` (
  `id` VARCHAR(45) NOT NULL,
  `NombreCiudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Empresa` (
  `id` VARCHAR(45) NOT NULL,
  `NombreEmpresa` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`CartaRemisora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`CartaRemisora` (
  `id` VARCHAR(45) NOT NULL,
  `idArticulo` VARCHAR(45) NULL,
  `idCliente` VARCHAR(45) NULL,
  `idUsuario` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Telefono` VARCHAR(20) NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Flete_Pagadero` VARCHAR(45) NULL,
  `Numero_Factura` VARCHAR(45) NULL,
  `Cantidad_Articulo` INT NULL,
  `Valor_Unitario_Articulo` INT NULL,
  `Valor_Total` INT NULL,
  `Numero_Bultos` VARCHAR(45) NULL,
  `Fecha_Creacion` DATETIME NULL,
  `Fecha_Modificacion` DATETIME NULL,
  `descripcion` VARCHAR(10000) NULL,
  `consecutivo` INT NULL,
  `Empresa` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `Fk_idArticulo`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `ProyectoDespacho`.`Articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `ProyectoDespacho`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_ciudad`
    FOREIGN KEY (`Ciudad`)
    REFERENCES `ProyectoDespacho`.`Ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_empresa`
    FOREIGN KEY (`Empresa`)
    REFERENCES `ProyectoDespacho`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_idArticulo_idx` ON `ProyectoDespacho`.`CartaRemisora` (`idArticulo` ASC);

CREATE INDEX `Fk_idUsuario_idx` ON `ProyectoDespacho`.`CartaRemisora` (`idUsuario` ASC);

CREATE INDEX `Fk_ciudad_idx` ON `ProyectoDespacho`.`CartaRemisora` (`Ciudad` ASC);

CREATE INDEX `Fk_empresa_idx` ON `ProyectoDespacho`.`CartaRemisora` (`Empresa` ASC);


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Prestamos` (
  `id` VARCHAR(45) NOT NULL,
  `id_Cliente` VARCHAR(45) NULL,
  `id_Usuario` VARCHAR(45) NULL,
  `id_Ciudad` VARCHAR(45) NULL,
  `id_Articulo` VARCHAR(45) NULL,
  `valorUnitario` INT NULL,
  `valortotal` INT NULL,
  `cantidad` INT NULL,
  `Fecha_Creacion` DATETIME NULL,
  `Fecha_Modificacion` DATETIME NULL,
  `consecutivo` INT NULL,
  `descripcion` VARCHAR(10000) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `cliente`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `ProyectoDespacho`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `ProyectoDespacho`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ciudad`
    FOREIGN KEY (`id_Ciudad`)
    REFERENCES `ProyectoDespacho`.`Ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `articulo`
    FOREIGN KEY (`id_Articulo`)
    REFERENCES `ProyectoDespacho`.`Articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cliente_idx` ON `ProyectoDespacho`.`Prestamos` (`id_Cliente` ASC);

CREATE INDEX `fk_usuario_idx` ON `ProyectoDespacho`.`Prestamos` (`id_Usuario` ASC);

CREATE INDEX `fk_ciudad_idx` ON `ProyectoDespacho`.`Prestamos` (`id_Ciudad` ASC);

CREATE INDEX `fk_articulo_idx` ON `ProyectoDespacho`.`Prestamos` (`id_Articulo` ASC);


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Area` (
  `id` VARCHAR(45) NOT NULL,
  `nombreArea` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Cargos` (
  `id` VARCHAR(45) NOT NULL,
  `nombreCargo` VARCHAR(45) NULL,
  `codigoSena` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Municipio` (
  `id` VARCHAR(45) NOT NULL,
  `nombreMunicipio` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`InformacionPersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`InformacionPersonal` (
  `cc` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fechaNacimiento` VARCHAR(45) NULL,
  `lugarNacimiento` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `rh` VARCHAR(45) NULL,
  `estadoCivil` VARCHAR(45) NULL,
  `tiempoCasado` VARCHAR(45) NULL,
  `numeroHijos` VARCHAR(45) NULL,
  `direccionResidencia` VARCHAR(45) NULL,
  `barrio` VARCHAR(45) NULL,
  `municipio` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `libretaMilitar` VARCHAR(45) NULL,
  `claseLibretaMilitar` VARCHAR(45) NULL,
  PRIMARY KEY (`cc`),
  CONSTRAINT `fk_municipio`
    FOREIGN KEY (`municipio`)
    REFERENCES `ProyectoDespacho`.`Municipio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_municipio_idx` ON `ProyectoDespacho`.`InformacionPersonal` (`municipio` ASC);


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`EstadoEstudiantil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`EstadoEstudiantil` (
  `id` VARCHAR(45) NOT NULL,
  `tituloCarrera` VARCHAR(45) NULL,
  `semestreActual` VARCHAR(45) NULL,
  `FechaTerminacion` VARCHAR(45) NULL,
  `estadoEstudiante` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`SeguridadSocial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`SeguridadSocial` (
  `id` VARCHAR(45) NOT NULL,
  `censantias` VARCHAR(45) NULL,
  `afp` VARCHAR(45) NULL,
  `eps` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`InformacionFamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`InformacionFamiliar` (
  `id` VARCHAR(45) NOT NULL,
  `ccEmpleado` INT NULL,
  `nombreFamiliar` VARCHAR(45) NULL,
  `parantesco` VARCHAR(45) NULL,
  `fechaDeNacimiento` VARCHAR(45) NULL,
  `edad` VARCHAR(45) NULL,
  `escolaridad` VARCHAR(45) NULL,
  `ocupacion` VARCHAR(45) NULL,
  `viveConEmpleado` VARCHAR(45) NULL,
  `dependeDelEmpleado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Contrato` (
  `id` VARCHAR(45) NOT NULL,
  `tipoContrato` VARCHAR(45) NULL,
  `fechaPrimerContrato` VARCHAR(45) NULL,
  `fechaIngreso` VARCHAR(45) NULL,
  `fechaDeRetiro` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`InformacionAcademica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`InformacionAcademica` (
  `id` VARCHAR(45) NOT NULL,
  `nombreEmpleado` VARCHAR(45) NULL,
  `escolaridad` VARCHAR(45) NULL,
  `tituloObtenido` VARCHAR(45) NULL,
  `institucion` VARCHAR(45) NULL,
  `primerCurso` VARCHAR(45) NULL,
  `segundoCurso` VARCHAR(45) NULL,
  `tercerCurso` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`InformacionVivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`InformacionVivienda` (
  `id` VARCHAR(45) NOT NULL,
  `numeroDeHabitantes` VARCHAR(45) NULL,
  `indiceHacimiento` VARCHAR(45) NULL,
  `estrato` VARCHAR(45) NULL,
  `tenenciaDeLaVivienda` VARCHAR(45) NULL,
  `tipoDeVivienda` VARCHAR(45) NULL,
  `numeroDeHabitacion` VARCHAR(45) NULL,
  `cocina` VARCHAR(45) NULL,
  `bañoComun` VARCHAR(45) NULL,
  `bañoPrivado` VARCHAR(45) NULL,
  `sala` VARCHAR(45) NULL,
  `comedor` VARCHAR(45) NULL,
  `salaComedor` VARCHAR(45) NULL,
  `zonaDeRopa` VARCHAR(45) NULL,
  `agua` VARCHAR(45) NULL,
  `electricidad` VARCHAR(45) NULL,
  `gas` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `internet` VARCHAR(45) NULL,
  `televisionPorCable` VARCHAR(45) NULL,
  `otros` VARCHAR(45) NULL,
  `television` VARCHAR(45) NULL,
  `equipoDeSonido` VARCHAR(45) NULL,
  `lavadora` VARCHAR(45) NULL,
  `estufa` VARCHAR(45) NULL,
  `dvd` VARCHAR(45) NULL,
  `microondas` VARCHAR(45) NULL,
  `pc` VARCHAR(45) NULL,
  `piso` VARCHAR(45) NULL,
  `techo` VARCHAR(45) NULL,
  `paredes` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`InformacionEconomica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`InformacionEconomica` (
  `id` VARCHAR(45) NOT NULL,
  `primerIngreso` VARCHAR(45) NULL,
  `segundoIngreso` VARCHAR(45) NULL,
  `otrosIngresos` VARCHAR(45) NULL,
  `totalIngresos` VARCHAR(45) NULL,
  `arriendo` VARCHAR(45) NULL,
  `serviciosPublicos` VARCHAR(45) NULL,
  `internet` VARCHAR(45) NULL,
  `telefonia` VARCHAR(45) NULL,
  `cable` VARCHAR(45) NULL,
  `alimentacion` VARCHAR(45) NULL,
  `transporte` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `educacion` VARCHAR(45) NULL,
  `vehiculo` VARCHAR(45) NULL,
  `prestacionesComercial` VARCHAR(45) NULL,
  `prestamosBancario` VARCHAR(45) NULL,
  `hipoteca` VARCHAR(45) NULL,
  `vestidoYCalzado` VARCHAR(45) NULL,
  `recreacion` VARCHAR(45) NULL,
  `saldoFinal` VARCHAR(45) NULL,
  `totalGastos` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`Dotacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`Dotacion` (
  `id` VARCHAR(45) NOT NULL,
  `camisa` VARCHAR(45) NULL,
  `calsado` VARCHAR(45) NULL,
  `pantalon` VARCHAR(45) NULL,
  `delantal` VARCHAR(45) NULL,
  `overol` VARCHAR(45) NULL,
  `botas` VARCHAR(45) NULL,
  `tenis` VARCHAR(45) NULL,
  `otrasDotaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`InformacionEmpleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`InformacionEmpleado` (
  `id` VARCHAR(45) NOT NULL,
  `codigoNomina` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `carnet` VARCHAR(45) NULL,
  `informacionAcademica` VARCHAR(45) NULL,
  `informacionPersonal` INT NULL,
  `informacionFamiliar` VARCHAR(45) NULL,
  `InformacionVivienda` VARCHAR(45) NULL,
  `InformacionEconomica` VARCHAR(45) NULL,
  `estadoEstudiantil` VARCHAR(45) NULL,
  `seguridadSocial` VARCHAR(45) NULL,
  `area` VARCHAR(45) NULL,
  `contrato` VARCHAR(45) NULL,
  `vehiculo` VARCHAR(45) NULL,
  `contactoEmergencia` VARCHAR(45) NULL,
  `telefonoContacto` VARCHAR(45) NULL,
  `dotacion` VARCHAR(45) NULL,
  `motivoRetiro` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `informacionpersonal`
    FOREIGN KEY (`informacionPersonal`)
    REFERENCES `ProyectoDespacho`.`InformacionPersonal` (`cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estadoestudiantil`
    FOREIGN KEY (`estadoEstudiantil`)
    REFERENCES `ProyectoDespacho`.`EstadoEstudiantil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seguridadsocial`
    FOREIGN KEY (`seguridadSocial`)
    REFERENCES `ProyectoDespacho`.`SeguridadSocial` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `informacionfamiliar`
    FOREIGN KEY (`informacionFamiliar`)
    REFERENCES `ProyectoDespacho`.`InformacionFamiliar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `area`
    FOREIGN KEY (`area`)
    REFERENCES `ProyectoDespacho`.`Area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contrato`
    FOREIGN KEY (`contrato`)
    REFERENCES `ProyectoDespacho`.`Contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `informacionacademina`
    FOREIGN KEY (`informacionAcademica`)
    REFERENCES `ProyectoDespacho`.`InformacionAcademica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `informacionvivienda`
    FOREIGN KEY (`InformacionVivienda`)
    REFERENCES `ProyectoDespacho`.`InformacionVivienda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `informacionEconomica`
    FOREIGN KEY (`InformacionEconomica`)
    REFERENCES `ProyectoDespacho`.`InformacionEconomica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dotacion`
    FOREIGN KEY (`dotacion`)
    REFERENCES `ProyectoDespacho`.`Dotacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cargo`
    FOREIGN KEY (`cargo`)
    REFERENCES `ProyectoDespacho`.`Cargos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fkempleado_idx` ON `ProyectoDespacho`.`InformacionEmpleado` (`informacionPersonal` ASC);

CREATE INDEX `fkestadoestudiantil_idx` ON `ProyectoDespacho`.`InformacionEmpleado` (`estadoEstudiantil` ASC);

CREATE INDEX `fk_seguridadsocial_idx` ON `ProyectoDespacho`.`InformacionEmpleado` (`seguridadSocial` ASC);

CREATE INDEX `fk_informacionfamiliar_idx` ON `ProyectoDespacho`.`InformacionEmpleado` (`informacionFamiliar` ASC);

CREATE INDEX `fk_contrato_idx` ON `ProyectoDespacho`.`InformacionEmpleado` (`contrato` ASC);

CREATE INDEX `informacionacademina_idx` ON `ProyectoDespacho`.`InformacionEmpleado` (`informacionAcademica` ASC);

CREATE INDEX `informacionvivienda_idx` ON `ProyectoDespacho`.`InformacionEmpleado` (`InformacionVivienda` ASC);

CREATE INDEX `informacionEconomica_idx` ON `ProyectoDespacho`.`InformacionEmpleado` (`InformacionEconomica` ASC);

CREATE INDEX `dotacion_idx` ON `ProyectoDespacho`.`InformacionEmpleado` (`dotacion` ASC);

CREATE INDEX `area_idx` ON `ProyectoDespacho`.`InformacionEmpleado` (`area` ASC);

CREATE INDEX `cargo_idx` ON `ProyectoDespacho`.`InformacionEmpleado` (`cargo` ASC);


-- -----------------------------------------------------
-- Table `ProyectoDespacho`.`ArticulosDeDotacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoDespacho`.`ArticulosDeDotacion` (
  `id` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `tipoDotacion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
